github.com:
    users:
        macehex:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: macehex
