version: 1
profile:
    email: macehelix@protonmail.com
    accountId: 712020:5058994d-b99a-4a37-9521-8f9e0016a49c
    auth_type: api_token
    token: !!binary |
        CJE8rz/2+UlRiM5X7jKT6HzO1A5mCeJRSOrSXt/5aQE6OjowMzcxYjlmZTFhYzE2ODMyYj
        hjNjY0NmE4NTQ0MzhiNDQ4ZjMzNTliNzY5NmNkOTU3NTMxZjg1ZTcwMWVjZTgyMTBmOTk5
        MmIxYjY5Y2M3NTI1MTc1MjBhODk4NDU1ZTczYThiNDEzMDBhMmRmNGEzNDYxYzg2MDY0NG
        ZiMDBhMThkNDYxMDU1N2JiNmNkNzI1NDYyNTllMWZjMzg3MDc4M2Q2NThmMWIwMzMxYzJh
        ODBhNDJhMzM1N2NlNDgwZDdmYWY5MmIyMTMwNDU3MmM3OGZmNWQ5YmE2YTFjM2I5NjQwY2
        Y2NDM4YTgyYzQyNTZhNjRlODRjZmY5ZjFlNzYxZmFiYmUxOWY2M2UyY2Y0MzY3YTM4ZjE1
        MGU0ODczZmEwMzVhYWViMjljOGExZWEzZmFiYTc1MDI3OTBhZjgyNjdhMmQwOTRkMzEyMj
        lhNDM2ZDQ3MmZhMjA2ODkwYjFmNTcyNjI0OTY0NmJjNzQ5Y2YzZTEyODA1Mzg3ZWNjYjFk
        YzczOGE0ODY4ODA3Yzg2YmM4OTE1ODkwOTgxZDk5MDBlY2Q1ZWY4MTY1YzhjN2MxMWNlMW
        UwOA==
